export const revealConfig = {
  couple: 'Luan & Sarah',
  babyName: 'Esther Lima',
  audioSrc: '/audio/revelacao.mp3',
  audioDuration: 178.608,
  memories: [
    { id: 'memory-1', src: '/photos/memoria-01.jpg', start: 3, end: 23, placement: 'memory-left', objectPosition: '50% 34%' },
    { id: 'memory-2', src: '/photos/memoria-02.jpg', start: 23, end: 43, placement: 'memory-right', objectPosition: '50% 32%' },
    { id: 'memory-3', src: '/photos/memoria-03.jpg', start: 43, end: 63, placement: 'memory-left-top', objectPosition: '27% 50%' },
    { id: 'memory-4', src: '/photos/memoria-04.jpg', start: 63, end: 83, placement: 'memory-right-bottom', objectPosition: '50% 28%' },
    { id: 'memory-5', src: '/photos/memoria-05.jpg', start: 83, end: 103, placement: 'memory-left', objectPosition: '50% 34%' },
    { id: 'memory-6', src: '/photos/memoria-06.jpg', start: 103, end: 130, placement: 'memory-right', objectPosition: '67% 38%' },
  ],
  timeline: [
    { id: 'story-1', start: 0, kind: 'story', text: 'Algumas histórias começam sem avisar.' },
    { id: 'story-2', start: 12, kind: 'story', text: 'Dois caminhos se encontraram.' },
    { id: 'story-3', start: 25, kind: 'story', text: 'O tempo passou.\nO amor cresceu.' },
    { id: 'story-4', start: 40, kind: 'story', text: 'Vieram os sonhos.\nVieram os planos.' },
    { id: 'story-5', start: 56, kind: 'story', text: 'Veio o sim.' },
    { id: 'story-6', start: 68, kind: 'story', text: 'E então...' },
    { id: 'story-7', start: 77, kind: 'story', text: 'Um novo coração começou a bater.' },
    { id: 'story-8', start: 90, kind: 'story', text: 'Antes mesmo de chegar,\njá existe tanto amor.' },
    { id: 'story-9', start: 101, kind: 'story', text: 'Alguns presentes chegam\nno tempo de Deus.' },
    { id: 'prepare-1', start: 108, kind: 'preparation', text: 'Agora chegou a hora.' },
    { id: 'prepare-2', start: 114, kind: 'preparation', text: 'Peguem o lança-confete.' },
    { id: 'prepare-3', start: 120, kind: 'preparation', text: 'Fiquem juntos.' },
    { id: 'prepare-4', start: 126, kind: 'preparation', text: 'Respirem fundo.' },
    { id: 'count-3', start: 134, kind: 'countdown', text: '3' },
    { id: 'count-2', start: 137, kind: 'countdown', text: '2' },
    { id: 'count-1', start: 140, kind: 'countdown', text: '1' },
    { id: 'reveal', start: 145, kind: 'reveal', text: 'É uma menina.' },
    { id: 'name-intro', start: 153, kind: 'nameIntro', text: 'E ela já tem nome.' },
    { id: 'name', start: 159, kind: 'name', text: 'Esther Lima' },
    { id: 'final', start: 169, kind: 'final', text: 'Esther Lima está chegando.' },
  ],
} as const;
export type TimelineItem = (typeof revealConfig.timeline)[number];
