export const revealConfig = {
  couple: 'Luan & Sarah',
  babyName: 'Esther Lima',
  audioSrc: '/audio/revelacao.mp3',
  audioDuration: 178.608,
  timeline: [
    { id: 'story-1', start: 0, kind: 'story', text: 'Algumas histórias começam sem avisar.' },
    { id: 'story-2', start: 12, kind: 'story', text: 'Dois caminhos se encontraram.' },
    { id: 'story-3', start: 25, kind: 'story', text: 'O tempo passou.\\nO amor cresceu.' },
    { id: 'story-4', start: 40, kind: 'story', text: 'Vieram os sonhos.\\nVieram os planos.' },
    { id: 'story-5', start: 56, kind: 'story', text: 'Veio o sim.' },
    { id: 'story-6', start: 68, kind: 'story', text: 'E então...' },
    { id: 'story-7', start: 77, kind: 'story', text: 'Um novo coração começou a bater.' },
    { id: 'story-8', start: 90, kind: 'story', text: 'Antes mesmo de chegar,\\njá existe tanto amor.' },
    { id: 'story-9', start: 101, kind: 'story', text: 'Alguns presentes chegam\\nno tempo de Deus.' },
    { id: 'prepare-1', start: 111, kind: 'preparation', text: 'Agora chegou a hora.' },
    { id: 'prepare-2', start: 119, kind: 'preparation', text: 'Peguem o lança-confete.' },
    { id: 'prepare-3', start: 127, kind: 'preparation', text: 'Fiquem juntos.' },
    { id: 'prepare-4', start: 135, kind: 'preparation', text: 'Respirem fundo.' },
    { id: 'count-3', start: 143, kind: 'countdown', text: '3' },
    { id: 'count-2', start: 148, kind: 'countdown', text: '2' },
    { id: 'count-1', start: 153, kind: 'countdown', text: '1' },
    { id: 'pause', start: 158, kind: 'pause', text: '' },
    { id: 'reveal', start: 161, kind: 'reveal', text: 'É uma menina.' },
    { id: 'name-intro', start: 167, kind: 'nameIntro', text: 'E ela já tem nome.' },
    { id: 'name', start: 171, kind: 'name', text: 'Esther Lima' },
    { id: 'final', start: 175, kind: 'final', text: 'Esther Lima está chegando.' },
  ],
} as const;
export type TimelineItem = (typeof revealConfig.timeline)[number];
